# Generated by Django 4.0.2 on 2022-04-07 18:17

from django.db import migrations
from django.contrib.auth.hashers import make_password as pw_hash
from fitness.models import MyUser


def add_superuser(a, b):
    a = MyUser(name='admin', email='admin@admin.com', password=pw_hash('admin'), is_staff=True, is_superuser=True)
    a.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_superuser)
    ]
