# Generated by Django 4.0.2 on 2022-02-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='height_in_inches',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='weight_in_pounds',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
