# Generated by Django 4.0.2 on 2022-02-19 21:27

from django.db import migrations
import fitness.managers


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_alter_myuser_options_myuser_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', fitness.managers.CustomUserManager()),
            ],
        ),
    ]
