# Generated by Django 4.0.2 on 2022-02-20 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_alter_myuser_date_joined_alter_myuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='height_in_inches',
            field=models.IntegerField(null=True),
        ),
    ]
