# Generated by Django 4.0.2 on 2022-02-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_myuser_height_in_inches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='height_in_inches',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
