# Generated by Django 4.0.2 on 2022-02-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_alter_myuser_height_in_inches'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='sex',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='weight_in_pounds',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
