# Generated by Django 4.0.2 on 2022-02-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(default='media/images/Blank_profile.jpg', upload_to='profile_pics'),
        ),
    ]
