# Generated by Django 4.0.3 on 2022-03-15 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_myuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='my_exercises',
            field=models.ManyToManyField(to='fitness.exercise'),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='equipment',
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.equipment'),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='muscle',
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.muscle'),
        ),
    ]
