# Generated by Django 4.0.3 on 2022-03-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_myuser_my_exercises_remove_exercise_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
