# Generated by Django 4.0.3 on 2022-03-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0013_alter_exercise_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
