# Generated by Django 3.2.8 on 2022-03-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_alter_exercise_muscle'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
