# Generated by Django 4.0.2 on 2022-04-07 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0016_auto_20220331_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermeal',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='usermeal',
            name='user',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='UserMeal',
        ),
    ]
