# Generated by Django 4.0.2 on 2022-04-07 15:44

from django.db import migrations
from nutrition.models import Meal

#This will create a food item that will be saved in the data base
def single_nutrition(apps, schema_editor):
    food_ex = Meal(name='Test', calories=600, protein=60, carbs=0, serving_size=1, serving_unit="Egg")
    food_ex.save()


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(single_nutrition) #Use RunPython to run the function
    ]