# Generated by Django 4.0.4 on 2022-04-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeal',
            name='calories',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usermeal',
            name='carbs',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usermeal',
            name='fat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usermeal',
            name='protein',
            field=models.IntegerField(null=True),
        ),
    ]
